### ISSUE TITLE
.add destroyer D5 down

### ISSUE THREAD

**Issue by folliejester** [Maxisthemoose/discord-battleship#1]
both user dmed the both `.add destroyer D5 down`, nothing happened

**Comment by seasaltsaige** [comment]
I havent looked at this project in over 6 months, so I might get to it eventually, but can you provide any more info? Is the prefix set to .? That kind of stuff

**Comment by seasaltsaige** [comment]
Hm, that is strange indeed, I'll need more information for sure, as I just tried it out with a test bot and it worked fine.
![image](https://user-images.githubusercontent.com/59546581/113893224-aaf6ba80-977b-11eb-8795-f55a0235a137.png)

**Comment by folliejester** [comment]
can i invite you to my server? i'm available at folliejester#2001
